# Copyright 2026 Colliery, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Python implementation of the BytePipe interface.

The BytePipe trait (defined in tests/test-plugin-smoke/src/lib.rs) has two
methods:

- ``reverse(data: bytes) -> bytes`` — declared ``#[wire(raw)]`` on the
  Rust side, so it crosses as raw bytes both ways with no encoding.
- ``name() -> str`` — typed control-plane method.

The ``__interface_hash__`` constant must match the hash the Rust macro
computes for the trait. We derive it via the ``fidius python-stub``
subcommand and bake it in here. Regenerate with:

    fidius python-stub \
        --interface tests/test-plugin-smoke/src/lib.rs \
        --trait-name BytePipe \
        --out tests/test-plugin-py-greeter/byte_pipe.py
"""

from fidius import method

# Generated by `fidius python-stub` against the BytePipe trait in
# tests/test-plugin-smoke/src/lib.rs. The integration test asserts this
# matches the runtime constant via PluginHost discovery.
__interface_hash__ = 0xDF233D1A5936EB5C


@method
def reverse(data: bytes) -> bytes:
    """Raw-wire method: reverse the input bytes."""
    return bytes(reversed(data))


@method
def name() -> str:
    """Typed control-plane method: identify the plugin."""
    return "py-byte-pipe"
