[project]
name = "fidius"
version_from = "cargo"

[output]
format = "markdown"
path = "docs/api"
template = "mkdocs-material"

[rust]
crates = [
    "crates/fidius-core",
    "crates/fidius-macro",
    "crates/fidius-host",
    "crates/fidius-cli",
    "crates/fidius",
    "crates/fidius-test",
]
