# Copyright 2026 Colliery, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""fidius — Python SDK for authoring Fidius plugins.

A fidius Python plugin is a regular Python module whose plugin functions are
decorated with :func:`method`. The host imports the module, looks up the
registered callables by name, and dispatches calls into them.

Minimal example::

    from fidius import method, PluginError

    @method
    def greet(name: str) -> str:
        return f"Hello, {name}!"

    @method
    def shout(text: str) -> str:
        if not text:
            raise PluginError("EMPTY_INPUT", "text must be non-empty")
        return text.upper()

The host validates the interface at load time via the ``__interface_hash__``
constant your module declares (typically generated by ``fidius python-stub``).
Hash mismatches surface as a clean load error rather than silent corruption.

Errors raised as :class:`PluginError` round-trip with their ``code``,
``message``, and ``details`` preserved on the host side. Other exceptions
become a generic ``code = "PYTHON_ERROR"`` with the formatted traceback in
``details``.
"""

from ._errors import PluginError
from ._registry import get_method, list_methods, method, reset_registry

__all__ = [
    "PluginError",
    "get_method",
    "list_methods",
    "method",
    "reset_registry",
]
