// Copyright 2026 Colliery, Inc. Licensed under Apache 2.0
//
// Non-Rust polyglot guest (FIDIUS-I-0025): a Go (TinyGo) implementation of the
// SAME `greeter` WIT as the Rust, Python, and JavaScript guests. Bindings are
// generated by wit-bindgen-go; TinyGo builds the WASM component. The fidius host
// loads and calls it identically.
package main

import (
	greeter "greetergo/internal/fidius/greeter/greeter"

	"go.bytecodealliance.org/cm"
)

type addResult = cm.Result[greeter.PluginErrorShape, int64, greeter.PluginError]

func init() {
	greeter.Exports.Greet = func(name string) string {
		return "Hello, " + name + "!"
	}
	greeter.Exports.Add = func(a int64, b int64) addResult {
		return cm.OK[addResult, greeter.PluginErrorShape, int64, greeter.PluginError](a + b)
	}
	greeter.Exports.EchoBytes = func(data cm.List[uint8]) cm.List[uint8] {
		src := data.Slice()
		out := make([]uint8, len(src))
		for i := range src {
			out[i] = src[len(src)-1-i]
		}
		return cm.ToList(out)
	}
	greeter.Exports.ProbeEnv = func() bool { return false }
	greeter.Exports.FidiusInterfaceHash = func() uint64 { return 0x0102030405060708 }
}

func main() {}
